[package]
name = "ezoauth"
version = "0.1.0"
authors = ["Jakob Hellermann <jakob.hellermann@protonmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
reqwest = { version = "0.10", default-features = false }
oauth2 = "4.0.0-alpha"

[dev-dependencies]
anyhow = "1.0"